spring.application.name=order-service


server.port = 8054

spring.datasource.url=jdbc:mysql://localhost:3306/ecomorderms?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Chicago
spring.datasource.username=root
spring.datasource.password=Srinath07

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#mandatory to add below properties if you are using any port number for eureka expect 8761
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


logging.level.com.netflix.eureka=off
logging.level.com.netflix.discovery=off